vscode:
  extensions:
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - dzannotti.vscode-babel-coloring@0.0.4:5Rlj2/kADFIl+crtoyiywQ==
    - HookyQR.beautify@1.5.0:mXo/OcopUVNHHxCPZWwlxQ==
    - oderwat.indent-rainbow@7.4.0:nth8lnJRnQu9NcWvNc9KPA==
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==